<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From_fromCity</name>
   <tag></tag>
   <elementGuidId>b48d2cf7-42da-4d28-941a-7d34beb7c721</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fromCity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fromCity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29b40d6d-e0eb-4ff5-b94e-1c65a373599f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fromCity</value>
      <webElementGuid>34fed2f5-3807-4501-bed6-d6754e4005d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>fromCityVal</value>
      <webElementGuid>3fa2b4f1-233f-4233-9dc1-a84a049bc4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0de842c4-be3f-4be8-8d07-bb188f31cb08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bussw_inputField font30 latoBlack</value>
      <webElementGuid>76efe703-d7e9-46db-b4b5-821ba1786f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Delhi, Delhi</value>
      <webElementGuid>dfe0f713-fe48-4d1d-9c11-d52cfd97b6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fromCity&quot;)</value>
      <webElementGuid>2e20427b-5f37-4cf7-bab2-055df4a3a7cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fromCity']</value>
      <webElementGuid>a7542306-e0c2-482b-9037-158e10e7c0fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/label/input</value>
      <webElementGuid>285c46a1-109d-490a-8215-3e12ff8a5585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>03f4ba64-089e-4aaf-9771-1315d12101c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fromCity' and @type = 'text']</value>
      <webElementGuid>0f14e8dc-6cf4-4761-88bc-e43418c4cc0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
