<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Pune, Maharashtra</name>
   <tag></tag>
   <elementGuidId>109c71c1-6994-4a87-bea1-ca234e7de61a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-autowhatever-1-section-0-item-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='react-autowhatever-1-section-0-item-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7197640b-d8b8-4033-9473-c91cf7dc4e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>286c43a8-bf38-491d-875c-d0852eaa8639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-autowhatever-1-section-0-item-0</value>
      <webElementGuid>337b55ac-fc13-4a31-9c95-6d581e2920cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c2d0bc48-0f51-4b57-996a-2b872ba37c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-autosuggest__suggestion react-autosuggest__suggestion--first react-autosuggest__suggestion--highlighted</value>
      <webElementGuid>2413b6e1-04ef-4ca6-aaa6-58c8a1e989a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-section-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f4c59932-abb2-40f4-8004-9aeb833cfecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-suggestion-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d5eba519-ccd4-4ce1-8836-b4c52047933d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pune, Maharashtra</value>
      <webElementGuid>5823c97d-3e30-49ba-8cba-4a55e15f2ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-autowhatever-1-section-0-item-0&quot;)</value>
      <webElementGuid>2ae47884-06fd-4b19-a5c3-4fe0d58bf1e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='react-autowhatever-1-section-0-item-0']</value>
      <webElementGuid>fe4c7ed1-6c79-4893-928d-16adcf985d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-autowhatever-1']/div/ul/li</value>
      <webElementGuid>f2d04006-1cb6-4085-8f3b-4511d71eaca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[1]/following::li[1]</value>
      <webElementGuid>f694fb5b-f451-4ae3-bc8e-7964e00b18df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From'])[1]/following::li[1]</value>
      <webElementGuid>62741507-4c52-4c2b-8f48-fe70eaa01ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pune Airport, Maharashtra'])[1]/preceding::li[1]</value>
      <webElementGuid>2af6246c-d0d1-4d89-a2b2-c6863527c70c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/ul/li</value>
      <webElementGuid>9dcc12cf-56ff-4dd2-be90-693f242727b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'react-autowhatever-1-section-0-item-0' and (text() = 'Pune, Maharashtra' or . = 'Pune, Maharashtra')]</value>
      <webElementGuid>27c81994-b6ec-4ad3-b995-ab5a588fb997</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
